### ISSUE TITLE
Two implementations of __counting_semaphore_impl_base::__acquire_slow()

### ISSUE THREAD

**Issue by GorNishanov** [ogiroux/semaphore#3]
It seems that there are two different definitions for `__counting_semaphore_impl_base::__acquire_slow()`:

One is at
```cpp
counting.hpp: 240
__semaphore_abi inline void __counting_semaphore_impl_base::__acquire_slow() {
    if (__frontbuffer.fetch_sub(2, std::memory_order_acquire) >> 1 > 0)
        return;
    auto const result = __semaphore_sem_wait(__semaphore);
   ...
```
and another is at

```cpp
semaphore.cpp:312:
__semaphore_abi void __counting_semaphore_impl_base::__acquire_slow()
{

    int old;
    details::__semaphore_exponential_backoff b;
#ifdef __semaphore_fast_path
    for (int i = 0; i < 2; ++i)
    {
#else //__semaphore_fast_path
    while (1)
    {
#endif //__semaphore_fast_path
        b.sleep();
        old = atom.load(std::memory_order_acquire);
        if ((old >> __shift) >= 1)
            goto done;
    }
    ...
```

**Comment by ogiroux** [comment]
Right. It depends on whether the configuration macro "__semaphore_sem" is defined or not, which indicates whether the OS semaphore should be used as the backing operation, or not. This is disabled when using CUDA because the GPU can't interoperate with the OS semaphore, in which case a backoff loop is used instead, on all platforms.

**Comment by ogiroux** [comment]
BTW, I should probably rewrite this one last time (it'll be the ~fourth), as we standardize the last final interface and I get to assume CUDA 10.x now.

**Comment by GorNishanov** [comment]
I am wondering if the semaphore you can build out of awesome `atomic_wait` and `atomic_notify_*` would be actually more efficient than whatever semaphore is offered by the OS (pthreads or Win32).

CreateSemaphore and friends were developed in ancient times before WaitOnAddress/WakeOnAddress.
